### ISSUE TITLE
Typography section doesn't allow decimal points in variant value input

### ISSUE THREAD

**Issue by prichter** [Mirrorful/mirrorful#104]
If you attempt to edit a typography variant, the variant value input won't permit addition of a value containing a decimal place.  Furthermore, if the value has been imported with a decimal place and you attempt to delete the digit after the decimal place, the decimal place disappears.  If you attempt to type another decimal place in the case of an imported decimal, the input displays NaN.

**Comment by alexdanilowicz** [comment]
Thanks for reporting this @prichter. Feel free to take it on!

**Comment by prichter** [comment]
Working on this now.
