### ISSUE TITLE
Add tooltip to variant square that is assigned as the base

### ISSUE THREAD

**Issue by prichter** [Mirrorful/mirrorful#107]
If you add a color in the editor, it automatically creates a "500" variant, which when edited shows the "Set as base" flag set.  If you delete this _variant_, because of the flag set, it also deletes the base color.  This is not immediately obvious before the fact.  Suggest a "500 (BASE)" description in tile to make this clearer, or similar mechanism.

**Comment by Teddarific** [comment]
Yep, this is indeed confusing, but expected behavior. I think perhaps the solution here is more education around what the `base` variant refers to and how it works. I think a tooltip might be the way to go here

**Comment by alexdanilowicz** [comment]
![image](https://user-images.githubusercontent.com/29822597/225162715-4d803d3a-a5f0-4b6d-91b1-84b02db8f06c.png)

As a user, I want to know which variant is assigned as my base. For example, if 500 is my base (which it is in the above screenshot) there should be a tooltip around an icon that makes it obvious this is my base value.

**Comment by prichter** [comment]
Could we change styling of the variant (say with a thicker border) to highlight this?

**Comment by alexdanilowicz** [comment]
Love the iteration @prichter!! Will let @Teddarific chime in on the PR directly.
