### ISSUE TITLE
Add Mirrorful VS Code extension

### ISSUE THREAD

**Issue by zachsnoek** [Mirrorful/mirrorful#112]
As an engineer, I'd like to have a way to quickly reference my project's Mirrorful tokens without starting the local editor. It'd be nice to have a VS Code extension that reads the Mirrorful config and displays the tokens, similar to the Mirrorful UI. Having the Mirrorful editor in an extension might also be useful 👀.

**Comment by DivyanshuelRed** [comment]
Hey @zachsnoek, I'm Divyanshu Can I work on this issue?

**Comment by zachsnoek** [comment]
> Hey @zachsnoek , I'm Divyanshu Can I work on this issue?

Hey @thealoneshadow, we should see if @alexdanilowicz / @Teddarific want to prioritize this.

**Comment by alexdanilowicz** [comment]
Hey! Apologies just now seeing this. @thealoneshadow what's your familiarity with building VSCode extensions? Down to prioritize this. I just want to make sure we set it up correctly. 

Do you have a propose set up or framework (like existing boilerplate code) you want to use?

**Comment by thealoneshadow** [comment]
No prior experience Give me sometime i will try with on of my projects and let you know.

**Comment by alexdanilowicz** [comment]
I'm going to close this issue for now as we need to scope this out a little more. Some mockups might help if anyone is interested in that.
