### ISSUE TITLE
Sort fontsizes by size 

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#113]
In this example, `0.75 rem` should be first, even if it was added last.

For now, we can just sort by unit. For example, you can sort the rems, then px, then em. Then you can avoid crazy math.

<img width="913" alt="Screen Shot 2023-03-08 at 3 46 18 PM" src="https://user-images.githubusercontent.com/29822597/223878482-909b9519-bf7d-46b4-9efa-f38790e1c7a5.png">

**Comment by joelcmk** [comment]
Hey Alex, I can help with this issue!

**Comment by alexdanilowicz** [comment]
Resolved
