### ISSUE TITLE
Clarify that you don't need to add a hyphen in variable name 

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#125]
As a user, when I'm naming a color, I'm confused it if must name it `primary-blue` because I'm used to variables not having spaces.

Solution: add a tooltip or make it more clear in some other way

**Comment by arneesh** [comment]
Hey @alexdanilowicz, I have given a merge request for this issue: [#144 ](https://github.com/Mirrorful/mirrorful/pull/144)
