### ISSUE TITLE
After running npx mirrorful, immediately pop up localhost:5050 like they do with create react app

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#127]
CRA - create react app - pops up localhost:5050 in your browser for you after running it. we should do the same. 

CRA is open-source. Need to see how they do it.

**Comment by Ujjwal55** [comment]
I would like to take up this issue @alexdanilowicz

**Comment by alexdanilowicz** [comment]
Hey @Ujjwal55, actually this has already been fixed in https://github.com/Mirrorful/mirrorful/pull/129. It seems Github did not automatically close the issue once the PR was merged. There are some other great first issues here if you're interested: https://github.com/Mirrorful/mirrorful/contribute

Welcome to the community 👋🏼 . Have you already joined our Slack? https://join.slack.com/t/mirrorful/shared_invite/zt-1ps2xtxh0-2NaixFfFzSKZbr5gw_AHfA
