### ISSUE TITLE
Two CSS colors missing from validCssColors.ts

### ISSUE THREAD

**Issue by prichter** [Mirrorful/mirrorful#132]
Tested against list taken from https://www.tutorialrepublic.com/css-reference/css-color-names.php, two colors are shown during testing as missing:  "navyblue" and "seagreen"

<img width="559" alt="image" src="https://user-images.githubusercontent.com/1085675/224544937-58ccb365-7e53-4597-b3d4-b8758a7b2f8b.png">

**Comment by prichter** [comment]
Good first issue - research that these are valid colors according to CSS spec, and update valid colors.

**Comment by alexdanilowicz** [comment]
Awesome, I just fixed this with #132. https://github.com/Mirrorful/mirrorful/commit/fbc3e0218d989599f3c678ebe4a4c6abcca8c05d

Closing!
