### ISSUE TITLE
Clear add color modal state on close

### ISSUE THREAD

**Issue by zachsnoek** [Mirrorful/mirrorful#142]
Demo: https://www.loom.com/share/1080d75392504e6ea7b73c5f3d0bc87b

Adding multiple colors is difficult because the modal state doesn't reset. See [this Slack message](https://mirrorful.slack.com/archives/C04QRA1GA4C/p1678668860067089?thread_ts=1678663135.944999&cid=C04QRA1GA4C).

**Comment by alexdanilowicz** [comment]
This is resolved.
