### ISSUE TITLE
Add ability to select which file types Mirrorful exports

### ISSUE THREAD

**Issue by zachsnoek** [Mirrorful/mirrorful#147]
We should let users select which file types Mirrorful exports because some/most projects don't need tokens in all formats. We can enable this by adding a property like `files` to the configuration object whose value is an array of export file types.

See [this Slack thread](https://mirrorful.slack.com/archives/C04QRA1GA4C/p1678668833244879?thread_ts=1678663135.944999&cid=C04QRA1GA4C).

**Comment by zachsnoek** [comment]
@alexdanilowicz / @Teddarific, feel free to assign this to me 🙋🏻

**Comment by alexdanilowicz** [comment]
Assigned, love it. I myself have been wanting this. Thanks for opening an issue so that it is tracked!
