### ISSUE TITLE
Support `rgba` on top of `hex`

### ISSUE THREAD

**Issue by Teddarific** [Mirrorful/mirrorful#150]
`rgb` in general allows for a bit more flexibility than hex colors. A setting to swap between hex and RGB would be amazing.

**Comment by alexdanilowicz** [comment]
@Teddarific FYI, we started this a it here: https://github.com/Mirrorful/mirrorful/pull/136

I think supporting alpha very important too, probably a separate issue

**Comment by Teddarific** [comment]
This one is trickier than it looks..

We need to update the color picker UI and everything.

![image](https://user-images.githubusercontent.com/16343600/226039863-cbcd6dce-9e96-47f7-90d1-6a7e06d7571d.png)

Figma for reference.

**Comment by alexdanilowicz** [comment]
@Teddarific adding alpha to color picker UI is just a prop.

**Comment by alexdanilowicz** [comment]
![image](https://user-images.githubusercontent.com/29822597/226041143-82298399-3dd3-4df9-a6a0-4a724f7b645f.png)

Just need to remove disableAlpha prop.

**Comment by Teddarific** [comment]
@alexdanilowicz Yeah, but everything else breaks. Need to update Inputs to include logic on what to do when there's an alpha (because Hex cannot consider alpha), and there's a bunch of logic around converting the Color Picker value into a readable hex value.

**Comment by alexdanilowicz** [comment]
Oh got it. Aligned. Thanks for explaining.

**Comment by waffleflopper** [comment]
> @alexdanilowicz Yeah, but everything else breaks. Need to update Inputs to include logic on what to do when there's an alpha (because Hex cannot consider alpha), and there's a bunch of logic around converting the Color Picker value into a readable hex value.

Hex Alpha is widely supported [per caniuse.com](https://caniuse.com/?search=alpha%20hexadecimal).  Would just include converting the alpha to a hex string, which is pretty straightforward.

```ts
function alphaToHex(alpha: number): string {
  const hex = Math.floor(alpha * 255).toString(16);
  return hex.padStart(2, '0');
}
```


Does the color picker pick with RGB Values?  Logic shouldn't be too tricky since converting the decimals to base 16 strings is trivial.

**Comment by Teddarific** [comment]
Good point that Hex Alpha would cover our bases! I still think we need to support `rgba` though, we want to be as flexible as possible, and also ideally consider users who are still building products that need to support IE (where Hex Alpha is not supported), but this can be a follow up thing.

The ideal situation is we can copy what Figma does:

![image](https://user-images.githubusercontent.com/16343600/228614231-a25232d5-716e-41f9-a75e-a66f30b1ff67.png)

**Comment by ktra99** [comment]
Maybe it would be good to isolate the color picker into its own component. Both the color token and the shadow token are using a color picker but they have a different setup. Perhaps it would be better to have a source of truth for all the parties to consume. I would be happy to work on this

**Comment by alexdanilowicz** [comment]
Sure go for it @ktra99 !

**Comment by alexdanilowicz** [comment]
Thanks so much for jumping in!!! @ktra99 🥳 🚀

**Comment by Teddarific** [comment]
@ktra99 That would be amazing, I think there's a cool opportunity here to create our own set of open-source components for defining styles (e.g. color picker, shadow editor, etc)

**Comment by alexdanilowicz** [comment]
Discussion happening in our Slack channel #rgba-color-picker: https://join.slack.com/t/mirrorful/shared_invite/zt-1ps2xtxh0-2NaixFfFzSKZbr5gw_AHfA

**Comment by alexdanilowicz** [comment]
Resolved by https://github.com/Mirrorful/mirrorful/pull/322
