### ISSUE TITLE
Add styled-components example

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#151]
Following the other examples in the `examples` directory, we should add an example for Mirrorful + [styled-components](https://styled-components.com/)

**Requirements:**
- use latest version of Mirrorful
- change the default index.js to actually consume the Mirrorful theme (don't just install Mirrorful)
- explain in the README how it works
- add example to top level readme and`packages/mirrorful/editor` README

**Comment by neilhsmith** [comment]
I'm looking for a first issue here and wouldn't mind taking this. One question - do you have a preference on which meta framework the example project will use? I'll likely use Next but curious if there's value in doing it in Vite since there's a CRA example but no Vite currently?

**Comment by alexdanilowicz** [comment]
Hey @neilhsmith welcome 👋🏼 , thanks for taking this one. There is no "official" preference. Next is great (as I would imagine that covers the most ground), but if you want to do it in Vite go for it.

**Comment by alexdanilowicz** [comment]
Hey @neilhsmith are you still interested in this? Btw, feel free to check out our slack workspace here! Lot of other contributors https://join.slack.com/t/mirrorful/shared_invite/zt-1ps2xtxh0-2NaixFfFzSKZbr5gw_AHfA

**Comment by neilhsmith** [comment]
Hey, sorry for the delay! I am but if someone else wants to take it, go for it. I'll join the Slack and find something when I free up in a few days if someone else does take this.

**Comment by Adefizzy** [comment]
Hi, @alexdanilowicz I will like to take up this issue.

**Comment by neilhsmith** [comment]
@Adefizzy I still haven't started so go ahead :)

I'm still planning on joining the Slack and can find another issue when I free up.

**Comment by Adefizzy** [comment]
Hi @alexdanilowicz , I have made a [PR](https://github.com/Mirrorful/mirrorful/pull/313/) for this issue

**Comment by alexdanilowicz** [comment]
Great work. Merging this in. Thanks @Adefizzy !
