### ISSUE TITLE
Add ability to manually reorder colors

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#152]
As a user, my "main" color might be purple, but I added purple last to Mirrorful. As a result, purple looks like it's not important because it's at the bottom, but in reality I use it all the time. For example, think about Doordashes theme: red is probably the most important color. 

Add ability to manually reroder colors. I think ideally there is some sort of drag and drop functionality as that is the most intuitive, but probably also the most complicated. This is more of a polish ticket, and we don't want to bloat the codebase, so let's discuss this a bit here before getting started.

**Comment by Teddarific** [comment]
Just to clarify, are you referring to re-ordering variants or colors?

**Comment by alexdanilowicz** [comment]
This issue was created from @zachsnoek's thread (feel free to chime in Zach), but IMO: reorder colors

For example:
```
BLUE

PURPLE
```

But then I add green, which is my new primary. I would green to come first.

For variants, I would expect them to be sorted in order: 50-900.

**Comment by karanvirsb** [comment]
Hey, can I be assigned to this issue?
