### ISSUE TITLE
Add vs Edit language — Clicking “Add New Font Size” show a modal with the title “Edit Font Size Variant”.

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#154]
Right now, the modal title says Edit when it should say Add (unless it already exists because then you are indeed "editing"). Should be a quick fix.

**Comment by gravityNotWorking** [comment]
I would like to take this issue. Additionally, I noticed that when we click on the `Add New Font Size` button, in the popup "Delete" button is still displayed. This should not be the case if we are adding a new font size.
