### ISSUE TITLE
Token objects generated for theme.js and theme.ts have unnecessary quotations around all property names 

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#155]
Token objects generated for theme.js and theme.ts have unnecessary quotations around all property names because we just throw the JSON.stringified version in there.

## Note:

A note: prettier usually cleans this up automatically if you touch the file, which is nice, but I see the value of this issue (which came from [Slack](https://mirrorful.slack.com/archives/C04QRA1GA4C/p1678663135944999)). I will say I like the simplicity of JSON.stringify, and I don’t think it’s worth a bunch of code to maintain/add to the project just to strip out the quotes. But if anyone thinks the solution will be simple, go for it!

**Comment by zachsnoek** [comment]
Hey, @alexdanilowicz –– you can assign this one to me. I have a change coming that should make this pretty straightforward.

Totally agree about the simplicity of `JSON.stringify` and maintenance cost. For nit-pickers like me, I think the extra polish  will be nice; having to manually run Prettier to strip the quotation marks is a little annoying 😅
