### ISSUE TITLE
Use actual color variable name in onboarding and export 

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#157]
As a user, when I look at the example import statement for both SCSS/CSS and JS/TS, I want it to reference one of my actual color names.

In the example import statements in BOTH the onboarding flow and the Export Modal, we should use the color name given, so that the user can just copy paste. 

For example, if the color name is "Globex Blue", the examples should reference "globex-blue" instead of the hardcoded "primary-color"

Please include a Loom / QA.

![image](https://user-images.githubusercontent.com/29822597/225162069-b02f1e43-9790-4df7-a028-34de5b2624e2.png)

**Comment by arneesh** [comment]
Hey @alexdanilowicz, I have given a pull request for this issue: [#164 ](https://github.com/Mirrorful/mirrorful/pull/164)
