### ISSUE TITLE
Validate that color name is not blank before saving

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#159]
A color name should never be empty.

**Comment by kunalznk** [comment]
can i work on this

**Comment by alexdanilowicz** [comment]
Go for it @kunalznk thanks for chiming in! Excited to see your contribution, this will be huge.

**Comment by kunalznk** [comment]
@alexdanilowicz thank you giving me a chance

**Comment by alexdanilowicz** [comment]
No problem @kunalznk. Thank you for your help. Let us know if you need anything.

**Comment by alexdanilowicz** [comment]
Hi @kunalznk are you still working on this?

**Comment by kunalznk** [comment]
Yes I'll raise pr today

**Comment by alexdanilowicz** [comment]
Great work @kunalznk ! well done! 🥳

**Comment by kunalznk** [comment]
Thanks ✌️
