### ISSUE TITLE
Color shade 50 doesn't align with the general scheme

### ISSUE THREAD

**Issue by ktra99** [Mirrorful/mirrorful#161]
<img width="1680" alt="Screenshot 2023-03-15 at 11 45 55" src="https://user-images.githubusercontent.com/82717216/225286292-3eac6100-77bd-47a5-9276-ad372e62d7a0.png">

**Comment by alexdanilowicz** [comment]
I think the idea of 50 is that it is actually quite light. This is intentional as sometimes you need to work with a very light color. Let's see if more people are confused by this, thanks for raising!

**Comment by ktra99** [comment]
Hmm I see. Perhaps it should be placed at the very start before 100. It sort of sticks out while being in the center of the color chain

**Comment by Teddarific** [comment]
@ktra99 Something I've been meaning to do, we should probably sort the hex colors! Im probably going to close this issue for now, since we are thinking about re-arranging things vertically to create a better UX
