### ISSUE TITLE
Fix horizontal scroll in the `Colors` tab

### ISSUE THREAD

**Issue by Teddarific** [Mirrorful/mirrorful#174]
![image](https://user-images.githubusercontent.com/16343600/225996127-f2a9a5d7-3a3a-4c15-9c16-f0c4b2d28f70.png)

There's some strange horizontal overflow in the Colors tab that's causing some weird UI jumps. Let's try to avoid just tossing in an `overflow-x: hidden` to figure out the root cause of this.

**Comment by ktra99** [comment]
Hey @Teddarific 

There seems to be multiple elements causing the overflow. I've recorded videos to show where the problems occur.

Desktop to small tablet: https://www.loom.com/share/67fd4e4bc33e4934a576590518000849

Mobile: https://www.loom.com/share/53a7c5063be24f989dbf1bfadc457a21

Don't know how responsive we want mirrorful to be but the component that seems to cause the most trouble at the moment is the `AddColorSkeleton.tsx`. I'd be happy to look into it further if needed.

**Comment by Teddarific** [comment]
Ah appreciate the looms, Kenny! In terms of responsiveness, responsiveness would be ideal, but I think we can assume that users will not be on mobile for now so not super concerned for smaller screen sizes, but I think we definitely want to work towards responsiveness.

I might play around later, but feel free to take a stab at it if you're interested — I've mainly been trying to figure out what exactly is causing horizontal overflow on a desktop screen!
