### ISSUE TITLE
🌎 Help us translate Mirrorful

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#18]
🌎 We want to let as many people use Mirorrful as possible! Help us translate it! 🚀

Translate our top-level README.

If you have any questions, just shoot them in the comments to this issue or [join our Slack](https://join.slack.com/t/mirrorful/shared_invite/zt-1ps2xtxh0-2NaixFfFzSKZbr5gw_AHfA).

**Comment by tobiasdossinger** [comment]
Hey there, I would be interested to translate it into German.

**Comment by alexdanilowicz** [comment]
@tobiasdossinger please also consider joining our Slack channel 👋🏼 : https://join.slack.com/t/mirrorful/shared_invite/zt-1ps2xtxh0-2NaixFfFzSKZbr5gw_AHfA

**Comment by tobiasdossinger** [comment]
@alexdanilowicz Sounds good, I already opened a PR for this: https://github.com/Mirrorful/mirrorful/pull/62 
I also had the same thoughts about the remaining two READMEs, which I commented in the PR. Thanks for having me!

**Comment by alexdanilowicz** [comment]
@tobiasdossinger incredible. thanks so much. Merged. Thanks for contributing and hopefully you can pick up some other issues and let us know how we can improve Mirrorful or get more in touch with the German open-source community. (We are from the United States, San Francisco!)

**Comment by joelcmk** [comment]
Hey Alex, I  can help to translate it to Spanish.

**Comment by gravityNotWorking** [comment]
Hi, I would like to translate to Turkish.

**Comment by rCirelli** [comment]
Hello there, I would like to translate to Portuguese.

**Comment by alexdanilowicz** [comment]
Hi @rCirelli, we would love your help with that! Feel free to mimic how other contributors did it. For example, https://github.com/Mirrorful/mirrorful/pull/99

**Comment by alexdanilowicz** [comment]
Hi everyone!

After much hard thought, we've unfortunately decided to sunset translations for the README.md file primarily because it has evolved so much in the past few months and we've struggled to keep it in sync across all the languages and changing documentation links.

This was a sad decision on our end but we're grateful for all the translations to date; it was wonderful seeing y'all come from different parts of the world to help translate. That said, we'll be revamping our contributor docs soon and adding in a contributor program entailing many more ways to contribute to Mirrorful from development to writing, etc. 😄
