### ISSUE TITLE
Add `build` Github action for `packages/mirrorful`

### ISSUE THREAD

**Issue by Teddarific** [Mirrorful/mirrorful#192]
Let's add Github actions that compile each package on PR to ensure that `main` is always in a pristine state.

**Comment by Saganic** [comment]
I'll take this.

**Comment by Teddarific** [comment]
Sweeeeet @Saganic, thanks for taking this one on!! Adding some additional color:

- Vercel covers us for web, and we don't actually super care about `packages/core` for now, so let's just start with one Github action for `packages/mirrorful`
- It might be a little bit tricky, because `packages/mirrorful` has `@mirrorful/core` as a dependency, and ideally we read off the local `@mirrorful/core` instead of pulling from NPM. Might need to do try to build `@mirrorful/core`, `yarn link`, and then build `packages/mirrorful` if that makes sense
