### ISSUE TITLE
Add lineHeight token to Typography section

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#194]
Along with fontSize, lineHeight should be a token in the Typography section.

Real world example: 

- You can see how a codebase that uses Mirrorful + Tailwind uses lineHeight and wants to consume lineHeight here: https://github.com/swishjam/swishjam/blob/main/dashboard/tailwind.config.js#L12

**Comment by alexdanilowicz** [comment]
For fontweight, it should be a dropdown with string values mapping to weight values, i.,e:

Check this out: https://design-tokens.github.io/community-group/format/#font-weight
<img width="841" alt="Screen Shot 2023-03-30 at 9 21 26 AM" src="https://user-images.githubusercontent.com/29822597/228901236-4e8d549f-8977-4166-8e81-7bbe7da730e4.png">

I will reassign to you.

**Comment by alexdanilowicz** [comment]
@Bismay5467 could you do #195 first and push that up and then we can assign you this one. See my comment here: https://github.com/Mirrorful/mirrorful/issues/195#issuecomment-1490585037 

@thealoneshadow are you still working on this one? I'll leave you assigned, but please let us know!

**Comment by DivyanshuelRed** [comment]
Yes @alexdanilowicz i am trying to understand the codebase right now. If @Bismay5467 had an idea so he can go ahead as well.

**Comment by alexdanilowicz** [comment]
@Bismay5467  anything that is a valid line-height CSS value is a possible unit: https://developer.mozilla.org/en-US/docs/Web/CSS/line-height
But I wouldn’t worry about the key word values (like normal, inherit) for now. Only the numbers. So to give a concrete example:

```
/* Unitless values
line-height: 3.5;
/* <length> values */
line-height: 3em;
/* <percentage> values */
line-height: 34%;
```

**Comment by alexdanilowicz** [comment]
Thanks for your help! @Bismay5467
