### ISSUE TITLE
Add a loading indicator on the initial fetch of store data

### ISSUE THREAD

**Issue by Teddarific** [Mirrorful/mirrorful#206]
Right now it just looks like an empty screen that then flashes to a certain state.

**Comment by alexdanilowicz** [comment]
Thanks for making an issue for this! I was going to!

Loom of this:
https://www.loom.com/share/e6debc45a4184dfcb1507b443986e0d3

As one can see, the empty dashboard flashes, then reads the store (if nothing is present, like in the Loom, it shows the onboarding modal), if something is present, it loads the data.

We need loading indicators!

**Comment by gravityNotWorking** [comment]
If no one is working on this issue, I would like to take it on!

**Comment by Teddarific** [comment]
I ended up taking this one @gravityNotWorking, but feel free to make it better! I tossed in a basic spinner for now haha
