### ISSUE TITLE
Expand export preview to be more than just colors. Should also show typography and shadow example

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#222]
Right now, in the export preview, all we show are colors. We should show how to import typography and shadows as well.

While we are here, might be also good to update the docs in `/docs`

<img width="818" alt="Screen Shot 2023-03-23 at 12 37 02 PM" src="https://user-images.githubusercontent.com/29822597/227331490-ff976397-f14a-403f-81bb-a90a0970eb84.png">

**Comment by karanvirsb** [comment]
Hey @alexdanilowicz can I be assigned to this issue?

**Comment by alexdanilowicz** [comment]
Sure go for it! @karanvirsb 🥳
