### ISSUE TITLE
Export tokens modal does not match what is actually exported out

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#224]
This should be fixed in both the CLI export modal and the web export modal.

1. `hover` is not even an option, yet is still shown
2. if the name has spaces, the spaces are shown in the export modal when they should not be.

![image](https://user-images.githubusercontent.com/29822597/227414574-d0d74f05-2770-48be-ab5f-6a19fd2f14ab.png)

<img width="424" alt="Screen Shot 2023-03-23 at 8 10 44 PM" src="https://user-images.githubusercontent.com/29822597/227414667-4d00e77f-99cc-4881-9a33-1efe1375d22f.png">

**Comment by kunalznk** [comment]
I'll fix this

**Comment by Teddarific** [comment]
I went ahead and fixed this already @kunalznk, but thanks for offering!
