### ISSUE TITLE
Clarify that everything can be changed later in onboarding modal

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#226]
As a user, I am confused why my primary color is automatically selected as my default/primary color in my components. 

Langauge like "this can be fine-tuned later" should be more visible and stated up front.

**Comment by rayyanQ** [comment]
Can I work on this issue?

**Comment by rayyanQ** [comment]
I have added the text, "You can customize each component later.", on a new line.
![Onboarding](https://user-images.githubusercontent.com/5747484/228993696-6d675fab-c1d9-426b-8e9f-ce3176f8ea99.png)

Let me know if this looks fine.
Alternatively, I can append ", this can be fine-tuned later." to the end.
