### ISSUE TITLE
In export modal, link to examples with frontend framework logos

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#227]
Remember to do this in both Web and CLI export modal.

We should show a React logo, a Next logo, a tailwind logo, a nuxt 3 logo, and link users to our documentation and to our example repos

**Comment by alexdanilowicz** [comment]
@karanvirsb once the NextJs router is merged in, this might be right up your alley if you are interested!

**Comment by alexdanilowicz** [comment]
Perhaps @Teddarific could share a quick mock if you are before you start

**Comment by karanvirsb** [comment]
Hey, @alexdanilowicz yeah I can take it on if the NextJs routing does not take too long.

**Comment by Pranav2612000** [comment]
Can I work on this?
