### ISSUE TITLE
If user is using tailwind, code mod the tailwind config file directly for the user

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#228]
As a user using tailwind, I do not want to have to manually extend my theme. 

Some thought needs to be given on how the user should "select" their tailwind theme to be edited, but we should just edit their `tailwind_config` file for them.

**Comment by karanvirsb** [comment]
Hey @alexdanilowicz can I take this one. Also do you have any ideas on if you want a button in the export modal or somewhere else to add the theme to tailwind?

**Comment by alexdanilowicz** [comment]
@karanvirsb apologies, I just saw this comment. Moving the discussion to the PR.

**Comment by alexdanilowicz** [comment]
Going to close this one. This was not completed, Github is wrong as marking it as completed, but more thought in general needs to be given to how we support tailwind users and automatically make their config for them. Right now, people just copy mirrorful tokens into their tailwind config. 

user feedback about tailwind and mirrorful:
> user goes in and edits colors on 3rd party tool, [tailwindshades.com](http://tailwindshades.com/) and copies the JSON over to the Mirrorful config
