### ISSUE TITLE
Add placeholder for add new shadow

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#236]
As a user who is not familiar with shadows and design tokens, if I choose to import my own theme, there is no shadow popular so i have no idea what the format is.

Acceptance criteria:
- add a placeholder value for name and value
- possible add a sample format subtitle if it looks good 

<img width="695" alt="Screen Shot 2023-03-24 at 10 06 15 PM" src="https://user-images.githubusercontent.com/29822597/227697492-1fc73f54-1cff-40de-87cf-13277731cdb3.png">

**Comment by gravityNotWorking** [comment]
@alexdanilowicz I would like to take it.

**Comment by alexdanilowicz** [comment]
@gravityNotWorking go for it! Thanks for jumping in, let us know if you need anything.

**Comment by Teddarific** [comment]
Hey @gravityNotWorking! As you're working on this, a better experience might be trying to copy Figma's shadow interface which makes it much more digestible than working with one massive string. The API might be different between a box shadow <> drop shadow, but worth thinking about!

<img width="225" alt="image" src="https://user-images.githubusercontent.com/16343600/227745408-ffd9da3f-3242-4a87-ad53-45df34a40a77.png">

**Comment by alexdanilowicz** [comment]
This is duplicated in: https://github.com/Mirrorful/mirrorful/issues/235
