### ISSUE TITLE
Clicking on color value automatically copies and paste it to clipboard

### ISSUE THREAD

**Issue by Teddarific** [Mirrorful/mirrorful#241]
<img width="124" alt="image" src="https://user-images.githubusercontent.com/16343600/227808911-9f88f149-3774-42b5-b47f-52a3e3b255d8.png">

For example, clicking on "#b59be9" should automatically c/p to my clipboard. 

Ideally, we add a basic hover state to indicate that the value is clickable.

CC @ktra99 for the idea!

**Comment by joelcmk** [comment]
Would it make sense to add this feature for the shadow boxes too?

**Comment by alexdanilowicz** [comment]
I think so @joelcmk! Maybe you can add that as a fast follow after your [PR](https://github.com/Mirrorful/mirrorful/pull/248) is merged
