### ISSUE TITLE
Clean up box shadow editing UI to support complex shadows

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#250]
As a user, if I have a box shadow  with multiple values (separated by commas), the editor UI breaks.

This is the result of https://github.com/Mirrorful/mirrorful/pull/248

If the box shadows value can be an array… then the editor needs a way to specify WHICH shadow you are editing. As the picker and sliders are only one array at a time. This is why Figma’s editor works because you only select one shadow at a time.

**Comment by ktra99** [comment]
I would like to work on this issue together with #257 as I believe both of these issues are interconnected

**Comment by joelcmk** [comment]
Hey Alex, I would like to help with this issue!

**Comment by alexdanilowicz** [comment]
@joelcmk awesome! You are the expert on this. Sounds good! Thanks Joel.

**Comment by joelcmk** [comment]
Awesome, before working on this! I would like to see if this is a good idea!

Now, the modal to edit/add a shadow looks like this. I don't think that it makes sense to have an input to edit the values when we already have sliders that do the same thing. Instead, we could add a div to show the output. 

<img width="533" alt="Screen Shot 2023-04-05 at 2 45 57 PM" src="https://user-images.githubusercontent.com/57118300/230189252-59687877-21fc-4a03-8557-a9faf90b1f0c.png">

I made a quick Figma to show how the changes would look like. I removed the inputs, add a button to add a new shadow (this would help for complex shadows), and added a box to input the result. 

<img width="485" alt="Screen Shot 2023-04-05 at 2 42 57 PM" src="https://user-images.githubusercontent.com/57118300/230191780-b2c18a98-c515-405c-81c7-bdc47bc1ca25.png">

Any feedback is appreciated!

**Comment by Teddarific** [comment]
Hey @joelcmk! Thanks for the mock up, helps a ton discussing this feature.

I know it makes this feature itself much more complicated, but I think we still need to include a way to enter in a raw value. People will find examples or come with their own box shadows, in which case they will want to simply copy and paste if that makes sense!

I think I would prefer inputs over sliders as well actually, as sliders aren't great for precise measurements. Let me know what you think!

**Comment by alexdanilowicz** [comment]
I agree with @Teddarific. Let us know if you have any thoughts here @joelcmk. Love how you originally implemented this, are now doing mockups, and then will take your feature to the next level! The true cycle of product development. Awesome stuff.

**Comment by alexdanilowicz** [comment]
Hey @joelcmk — fyi @ktra99 is working on refactoring the color picker a bit. Have you started this yet?

**Comment by joelcmk** [comment]
Hey Alex, yes I'm working on those changes. I hope that it won't create any conflicts with the refactoring!
