### ISSUE TITLE
Add svelte/SvelteKit example

### ISSUE THREAD

**Issue by waffleflopper** [Mirrorful/mirrorful#252]
With growing popularity of svelte and SvelteKit it would be good to add an example for it.

**Comment by alexdanilowicz** [comment]
Love this idea, thanks for opening @waffleflopper. Would you be interested in adding this example?

**Comment by sugamadhiakri** [comment]
Let me try? @alexdanilowicz

**Comment by alexdanilowicz** [comment]
@sugamadhiakri awesome, thanks for jumping in. Assigned to you. @sugamadhiakri
