### ISSUE TITLE
Refreshing the page resets the current tab.

### ISSUE THREAD

**Issue by gravityNotWorking** [Mirrorful/mirrorful#253]
If you refresh the page while in the shadows or typography section, it will automatically return to the first tab which is colors section.

![Recording 2023-03-29 at 16 22 16](https://user-images.githubusercontent.com/77449139/228551759-714e21a8-66b2-4138-88bb-c71d2fc125a9.gif)

**Comment by Teddarific** [comment]
@gravityNotWorking Yep, this would be nice to fix. I think we'll need to implement routing, which shouldn't be too bad!

Might be a bit of a refactor, but definitely worth it if anyone is interested in taking this one on!

https://nextjs.org/docs/routing/introduction

**Comment by JoshuaRotimi** [comment]
@Teddarific @alexdanilowicz Can you assign this to me? I would like to work on it. Thanks.

**Comment by Teddarific** [comment]
@JoshuaRotimi  this is actually fixed now with our latest change in #263! If you're looking for another good issue, maybe this one? https://github.com/Mirrorful/mirrorful/issues/270

**Comment by alexdanilowicz** [comment]
@JoshuaRotimi also consider joining our slack! https://join.slack.com/t/mirrorful/shared_invite/zt-1ps2xtxh0-2NaixFfFzSKZbr5gw_AHfA

**Comment by JoshuaRotimi** [comment]
Oh alright. I'll look at #270. I will be joining the slack as well. Thanks @alexdanilowicz @Teddarific
