### ISSUE TITLE
Create a Bootstrap Example

### ISSUE THREAD

**Issue by Teddarific** [Mirrorful/mirrorful#260]
Create an example of Mirrorful working with Bootstrap

**Comment by alexdanilowicz** [comment]
Should mimic the examples here: https://github.com/Mirrorful/mirrorful/tree/main/examples

Use that latest version of mirrorful.

**Comment by semijacks** [comment]
I'll work on this @alexdanilowicz 
Is there any particular framework you'd like to be used?

**Comment by alexdanilowicz** [comment]
@semijacks no, whatever you like. I think Next + React might be a good choice though.
