### ISSUE TITLE
Convert the onboarding steps into `<form />` elements

### ISSUE THREAD

**Issue by Teddarific** [Mirrorful/mirrorful#267]
Let's convert each of the pages in `Onboarding` to a `<form />` with an `onSubmit` so hitting enter works.

**Comment by Pranav2612000** [comment]
Hey @alexdanilowicz 
I'll like to work on this issue

**Comment by alexdanilowicz** [comment]
@Pranav2612000 go for it! Thank you!

**Comment by Pranav2612000** [comment]
Thank you @alexdanilowicz 
Just to confirm, the changes are to be done to the service in  the `apps/web` directory. Right?

That is, this page and the onboarding flow
![image](https://user-images.githubusercontent.com/20909078/229407181-b1b03d48-233a-4edd-9166-dfdbb53ff509.png)

**Comment by Teddarific** [comment]
@Pranav2612000 yep exactly! Just note that the components actually live in `packages/core`, but the project itself is run from `apps/web`

If you have any trouble running it, feel free to ping us in our Slack community: https://join.slack.com/t/mirrorful/shared_invite/zt-1ps2xtxh0-2NaixFfFzSKZbr5gw_AHfA
