### ISSUE TITLE
Update all examples to be on the latest version of mirrorful 

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#269]
For example, CRA is behind.

**Comment by nyeno** [comment]
Hi Alex, I am a first timer. By updating the example files, do you mean the config.json in the mirrorful folders?

**Comment by nyeno** [comment]
Hi Alex, I am a first timer. By updating the example files, do you mean the config.json in the mirrorful folders?

**Comment by alexdanilowicz** [comment]
Hi, thanks for jumping in @nyeno appreciate your help. I see we responded [here](https://mirrorful.slack.com/archives/C04RR2D7C65/p1680569142933099?thread_ts=1680444522.164459&cid=C04RR2D7C65) in Slack, but:

1. Going through the examples in the examples folder, and in each project, running: `yarn add mirrorful@latest `(which upgrades Mirrorful to the latest version)

2. And then asserting that after upgrading, the project still runs!

**Comment by alexdanilowicz** [comment]
So given the Create React App example, we need to update Mirrorful to 5.0.7 here in the package.json: We also need to update Mirrorful to version 5.0.6 (the latest) here in the package.json: https://github.com/Mirrorful/mirrorful/blob/main/examples/create-react-app/package.json#L39
