### ISSUE TITLE
docs: Use CodeGroup Mintifly component to clean up SCSS vs CSS vs Tailwind vs JS on the export formats sections

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#275]
https://mintlify.com/docs/components/code-group

In other words, take a look at the docs edited in this PR, and convert the headers to just use a CodeGroup

so instead of 

```
## CSS

## Tailwind

...

```

should be 

```


<CodeGroup>


... code goes here, reference https://mintlify.com/docs/components/code-group

</CodeGroup>
```

**Comment by zishanPathan** [comment]
I'm Interested in this issue Please assign me this issue.

**Comment by Bingolast** [comment]
Heyy anyone working on this issue?

**Comment by alexdanilowicz** [comment]
No one is working on it yet, go for it @zishanPathan. @Bingolast there are plenty of other issues if you're interested!

**Comment by alexdanilowicz** [comment]
Considering joining out Slack community to meet other contributors: https://join.slack.com/t/mirrorful/shared_invite/zt-1ps2xtxh0-2NaixFfFzSKZbr5gw_AHfA

@Bingolast @zishanPathan
