### ISSUE TITLE
[FR] Allow user to try out Typographies on custom placeholder text

### ISSUE THREAD

**Issue by Pranav2612000** [Mirrorful/mirrorful#294]
Right now, the user can just see the different Typography styles on the default `Lorem Ipsum` placeholder text. 
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/20909078/230732654-2e74008d-3103-48f9-92d9-4da3c1e69ca4.png">

It would be helpful if the user is able to customize the placeholder text and actually be able to see how his text looks in the chosen font. ( Similar to google fonts ) Thoughts? @alexdanilowicz @Teddarific 

This could be implemented by adding an input box at the top of the page ( between Typography heading and Font-Sizes ) which allows user to customize the placeholder text.

**Comment by alexdanilowicz** [comment]
<img width="1445" alt="Screen Shot 2023-04-10 at 2 15 42 PM" src="https://user-images.githubusercontent.com/29822597/231000385-6ba0472b-1e36-4733-9eeb-6fc77ba9c082.png">

https://fonts.google.com/specimen/Roboto?preview.text=Idea%20of%20how%20to%20test%20Mirrorful%20fonts,%20custom%20input&preview.text_type=custom

Love this idea. Yes @Pranav2612000 , go for it. Assigning to you!

**Comment by alexdanilowicz** [comment]
@Pranav2612000 how is this coming along? Let us know if you need anything!

**Comment by Pranav2612000** [comment]
Hey @alexdanilowicz 
Will complete it in a couple of days. 
I was away last weekend on a vacation, so wasn't able to give time to this.

**Comment by Pranav2612000** [comment]
Where do we want the inputbox?

1. 
![image](https://user-images.githubusercontent.com/20909078/232953065-32b7e322-38aa-40b7-bbe6-9fb0d22dc404.png)


2. 
![image](https://user-images.githubusercontent.com/20909078/232953469-583507aa-b482-424c-a808-63e7138ee9ad.png)


Or do you have anything else in mind? @alexdanilowicz

**Comment by Pranav2612000** [comment]
Also from the implementation POV, Inputbox is present in the `TypographyPage` component and the `Lorem ipsum...` text exists 5 levels deep inside `FontSizeRow` component. How do we want to pass this value from `TypographyPage` to `FontSizeRow`. Some options are -

1. We use props drilling to pass the value through all the intermediate components
2. We already have a typography Store ( `typographySlice.ts` ). We can add another property, say `meta` which contains this value ( similar values in the future will be stored here - value used for rendering and prevent props drilling) to the store and have the `FontSizeRow` subscribe to changes to it.
3. We can create a different store altogether. ( Again, this store has values used for rendering and prevent props drilling) If we decide to go ahead with this approach, should the store be seperate for each page or should we use a common store for all pages

Let me know your thoughts on this as well.

**Comment by alexdanilowicz** [comment]
Re: input box, I like option 2 for now.

Regarding how to pass the values, I think prop drilling is fine! 

Thanks for the questions! @Pranav2612000

**Comment by Pranav2612000** [comment]
Thank you. I'll have a PR ready soon.
