### ISSUE TITLE
Include example projects within the npm workspace

### ISSUE THREAD

**Issue by sugamadhiakri** [Mirrorful/mirrorful#301]
A penny for your thoughts: is it a good idea?

**Comment by alexdanilowicz** [comment]
What do you mean? 

Do you mean expanding the list here in the README? please feel free to add them yes to the examples section: https://www.npmjs.com/package/mirrorful

Otherwise what do you mean?

**Comment by alexdanilowicz** [comment]
@sugamadhiakri would love to hear what you mean? Could you give an example?

**Comment by alexdanilowicz** [comment]
I think this is the result of how we have yarn workspaces set up: https://classic.yarnpkg.com/lang/en/docs/workspaces/
