### ISSUE TITLE
Bug: Not checking "automatically generate variants" still generates variants

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#303]
<img width="858" alt="Screen Shot 2023-04-11 at 12 20 05 PM" src="https://user-images.githubusercontent.com/29822597/231267084-b8f8ad41-188f-48c6-8925-39401c37f568.png">

Expected behavior, if not checked, no variants are generated.

**Comment by Teddarific** [comment]
Fixed: https://github.com/Mirrorful/mirrorful/commit/7b2b143a1776a291f4e09527dbb2889f9cf97dde
