### ISSUE TITLE
Bug: Not all file types are on by default 

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#304]
As a user, when I first boot up Mirrorful, all file types should be on by default.

**Comment by alexdanilowicz** [comment]
When I just booted it up by running `npx mirrorful` in a new project, it seems everything was deselected.

**Comment by alexdanilowicz** [comment]
Hi @Sirjan-Singh — all of these should be selected by default. 
<img width="563" alt="Screen Shot 2023-04-13 at 11 55 43 AM" src="https://user-images.githubusercontent.com/29822597/231856624-f35afefd-8f34-40bf-bc73-4dda9c67f82e.png">

**Comment by veenaamb** [comment]
Please let me know if any changes are required [#324](https://github.com/Mirrorful/mirrorful/pull/324)

**Comment by haszankauna** [comment]
hello @alexdanilowicz can I please be assigned this issue?

**Comment by alexdanilowicz** [comment]
Hi @haszankauna I think @veenaamb fixed this in #324. But let us know if you're interested in any other issues and consider joining our slack channel: https://join.slack.com/t/mirrorful/shared_invite/zt-1ps2xtxh0-2NaixFfFzSKZbr5gw_AHfA
