### ISSUE TITLE
Warn user that you cannot have variants of the same name

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#306]
As a user, if I accidentally name a variant with a name that I already have, then it will overwrite the old one.

**Comment by nagy-nabil** [comment]
should it be implemented by throwing errors in `onUpdateVariant` and then catching any errors, or adding a new prop that checks data integrity in the store first, I would choose to go with the first approach, what do you think?

```ts
export function EditVariantModal({
  isOpen,
  onClose,
  initialVariant,
  onUpdateVariant,
  onDeleteVariant,
}: {
  isOpen: boolean
  onClose: () => void
  initialVariant?: TNamedToken
  onUpdateVariant: (newVariant: TNamedToken) => void  ---------->>>> THROW HERE
  onDeleteVariant?: () => void
}) {
```

**Comment by nagy-nabil** [comment]
@alexdanilowicz  is that how you want to warn the user?
![image](https://user-images.githubusercontent.com/65990275/231577695-fa4a553b-b54e-4fbd-85f2-463900ec50be.png)
