### ISSUE TITLE
📟 Help us add examples that use Mirrorful

### ISSUE THREAD

**Issue by semijacks** [Mirrorful/mirrorful#357]
## 📟 We want as many examples as possible that use Mirrorful! Help us! 🚀

Here are some of the frameworks/setups we are looking for: (👀 - looking for; ⚠️ - being worked on). And feel free to add your own. 

| **Framework** | **Status** |
|--------|--------|
| Remix | ✅ |
| Astro | ⚠️ | 
| Solid | 👀 | 

## Steps

_(copy these over to your PR description to check that you've done everything)_

1. [ ] Add a new example project to the `examples` directory
2. [ ] Make sure it uses the latest version of Mirrorful (note that some old examples may use older version, so don't copy an old example blindly!) . You should run: `npm i mirrorful@latest --save-dev`
3. [ ] Add a README that includes an explanation of how Mirrorful is set up and how to run it. 
4. [ ] ‼️  IMPORTANT: Your project should import Mirrorful and have code that uses theming that comes from Mirrorful
5.  [ ] Add your example to the top-level [README](https://github.com/Mirrorful/mirrorful) in the `## Component Library Agnostic` section
6.   [ ] Add your example to the sub-level [README](https://github.com/Mirrorful/mirrorful/tree/main/packages/mirrorful) in the `## Component Library Agnostic` section.
7.  [ ] Add your example to our [documentation](https://github.com/Mirrorful/mirrorful/blob/main/docs/home/examples.mdx) in the `docs/` folder
8.  [ ] Add your example to the list in the app here: https://github.com/Mirrorful/mirrorful/blob/main/packages/core/src/components/ExportSuccessModal.tsx (screenshot below):
 
<img width="732" alt="Screen Shot 2023-04-25 at 12 22 31 PM" src="https://user-images.githubusercontent.com/29822597/234381435-7df9cfd3-dbcf-4dc9-828b-a7f5ce22422c.png">

Finally, push up a PR! 👏🏼 

Thanks for all your help. 🚀

**Comment by alexdanilowicz** [comment]
As we are moving towards a web-based editor (Mirrorful Cloud), going to sunset this issue for now, but thank you for all those that helped!
