### ISSUE TITLE
Add copy to clipboard icon for each of the token export screenshots

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#36]
As a user, I would love to be able to copy paste theses.

Long-term, this would probably live in actual docs.

<img width="509" alt="Screen Shot 2023-02-23 at 12 47 52 AM" src="https://user-images.githubusercontent.com/29822597/220859982-1b21c3bf-0b23-4bfa-8869-3f63e4d5732f.png">

**Comment by imrishabh18** [comment]
Hey! I would like to take this up.

**Comment by alexdanilowicz** [comment]
Hey @imrishabh18 go for it! Could you please join our Slack community first: https://join.slack.com/t/mirrorful/shared_invite/zt-1ps2xtxh0-2NaixFfFzSKZbr5gw_AHfA and let us know if you have any questions. Apologies for the delayed response.

Let's use the Charka CopyIcon for this, as we already have Charka icons imported. 

You can import as

```javascript
import {
  CopyIcon,
} from '@chakra-ui/icons'
```

To get started, here's how you can run mirrorful locally after forking:

```
➜  mirrorful git:(main) ✗ cd packages/mirrorful/editor
➜  mirrorful git:(main) ✗ git checkout -b "imrishabh/issue-36"
➜  mirrorful git: ✗ yarn; cd editor; yarn; cd .. # install packages
➜  mirrorful git: ✗ yarn run local # runs mirrorful locally

$ rm -rf ./dist; tsc --build; cross-env NODE_ENV=development node ./dist/cli/index.js
Running Mirrorful version: 2.0.19
Starting Mirrorful in /Users/zeus/code/mirrorful/packages/mirrorful.


Visit: http://localhost:5050/
Inside your project, you can run:

  yarn run mirrorful

to start the visual editor at any time 🚀
```

Then you can edit the code and make your changes!

**Comment by alexdanilowicz** [comment]
Hey @imrishabh18 are you working on this? Otherwise might re-assign. Just let us know!

**Comment by lagneshthakur** [comment]
@alexdanilowicz please assign this to me, if @imrishabh18 is not available for now

**Comment by imrishabh18** [comment]
Sorry @alexdanilowicz, was busy lately. I had already made the changes, I will push the PR now

**Comment by lagneshthakur** [comment]
I am working on it, it's taking a little longer than expected but going good.
