### ISSUE TITLE
Example links are duplicated in docs 

### ISSUE THREAD

**Issue by purupurupu** [Mirrorful/mirrorful#369]
The following docs had duplicate links.
It may be better to unify one or the other so users do not get confused.
Sorry if that's what you intended to do.

URL
https://github.com/Mirrorful/mirrorful/blob/main/docs/home/examples.mdx

Corresponding link
[With Next.js](https://github.com/Mirrorful/mirrorful/tree/main/examples/with-chakra-ui)
[With Chakra UI](https://github.com/Mirrorful/mirrorful/tree/main/examples/with-chakra-ui)

**Comment by alexdanilowicz** [comment]
Ah yes, do you want to fix @purupurupu?

**Comment by purupurupu** [comment]
@alexdanilowicz 
Yes.Can I assign me?

**Comment by purupurupu** [comment]
I will I will change link to linear-example, like below.
[With Next.js](https://github.com/Mirrorful/mirrorful/tree/main/examples/linear-example)
