### ISSUE TITLE
Better Design / UI for the Server Ended Screen

### ISSUE THREAD

**Issue by karanvirsb** [Mirrorful/mirrorful#388]
There is the current page! Any suggestions or designs will help.

A Figma mockup would be great, and then @alexdanilowicz is happy to implement it.
![image](https://user-images.githubusercontent.com/71354242/235565095-1ea1d724-3e5c-4db9-ab3f-7ab1a2fa02d3.png)

**Comment by alexdanilowicz** [comment]
Closing this and will reopen once https://github.com/Mirrorful/mirrorful/pull/197 is opened.
