### ISSUE TITLE
Minor Bugs under Typography section

### ISSUE THREAD

**Issue by Bismay5467** [Mirrorful/mirrorful#394]
- If the placeholder value in the typography section is an empty string, the fontsize token will show the default content. Fontweight and lineheight tokens, on the other hand, do not display any default text.

- The default value for the fontsize and lineheights variation value input box in the edit or add modals is set to 0 and cannot be deleted when editing the input field. When entering a new value, the input is concatenated with the existing value i.e. 0, which can lead to a poor user experience. We can use a string type instead of a number type for variantValue. As in the fontweight edit(add) modal, we can simply display an error message for every non-numeric value entered. @alexdanilowicz Thoughts?

**Comment by noobCode-69** [comment]
Please review and merge!
