### ISSUE TITLE
Add button to delete shadows

### ISSUE THREAD

**Issue by joelcmk** [Mirrorful/mirrorful#395]
As a user, currently, it is not possible to delete a shadow that was added in error. The only way to remove it is to delete the entire variant and create a new one, which can be cumbersome and time-consuming. To make the process more efficient and user-friendly, an option should be added that allows the user to delete a shadow when they hover over it. This would enable users to easily correct mistakes without having to redo their work.

<img width="444" alt="Screen Shot 2023-05-05 at 12 46 11 PM" src="https://user-images.githubusercontent.com/57118300/236542893-1cc9792d-1305-4213-8b0b-faea87ea4c5d.png">

**Comment by alexdanilowicz** [comment]
great issue @joelcmk. 

Would you be interested in taking this on?

**Comment by alexdanilowicz** [comment]
If so, go for it!

**Comment by noobCode-69** [comment]
I will be willing to take this, looks challenging and nice!!

**Comment by alexdanilowicz** [comment]
I see this PR address this issue: https://github.com/Mirrorful/mirrorful/pull/398

@noobCode-69 great work, in the future, though, let's make a separate PR for each issue
