### ISSUE TITLE
Update typography modal

### ISSUE THREAD

**Issue by joelcmk** [Mirrorful/mirrorful#396]
To ensure a consistent design across different primitives, I have identified some minor improvements that could be made to the typography:

1.  Change the color of the "save" button to gray instead of green, to align with the overall color scheme of the interface.
<img width="96" alt="Screen Shot 2023-05-05 at 2 32 22 PM" src="https://user-images.githubusercontent.com/57118300/236552840-12855bf1-6372-4748-9269-49d22eda6a6e.png">

2. Move the "save" button to the right side when editing a variant, to make it more accessible and consistent with the placement of other buttons in the interface.
<img width="172" alt="Screen Shot 2023-05-05 at 2 33 27 PM" src="https://user-images.githubusercontent.com/57118300/236553035-4f1b239e-3d1a-419e-96ab-62dfe6e37f2a.png">

3. Add a red border to any input field that is missing information, to clearly indicate to the user which field requires attention and prevent errors.
<img width="482" alt="Screen Shot 2023-05-05 at 2 33 57 PM" src="https://user-images.githubusercontent.com/57118300/236553135-e2c5133e-b3d2-497a-8b1e-506860314493.png">

Implementing these changes would improve the overall user experience and enhance the visual consistency of the interface.

**Comment by Pranav2612000** [comment]
@alexdanilowicz I'll be interested in picking this up.

**Comment by alexdanilowicz** [comment]
@Pranav2612000 go for it! Thanks for the making the issue @joelcmk

**Comment by noobCode-69** [comment]
Please review and merger!!!

**Comment by alexdanilowicz** [comment]
@noobCode-69 merging this in. In a separate PR, as a fast follow, do you want to fix how this looks in the dark theme? The and disabled values Xs look a little off in the dark theme. 
<img width="416" alt="Screen Shot 2023-05-12 at 7 03 19 PM" src="https://github.com/Mirrorful/mirrorful/assets/29822597/a211f1ad-bbfd-415f-bfb0-1edca1ac62ab">

https://github.com/Mirrorful/mirrorful/issues/426
