### ISSUE TITLE
Shadows page : Warning: Each child in a list should have a unique "key" prop

### ISSUE THREAD

**Issue by noobCode-69** [Mirrorful/mirrorful#400]
* On the shadow page you will see there is an warning of 
**Warning: Each child in a list should have a unique "key" prop.**
* This can sometimes lead to unnatural behaviours.
* Needs to figure out why this is happening and fix it.

**Comment by noobCode-69** [comment]
Please assign this to me!

**Comment by noobCode-69** [comment]
Hey @alexdanilowicz , Please assign this task to me!

**Comment by alexdanilowicz** [comment]
@noobCode-69 assigned!

**Comment by Pranav2612000** [comment]
@noobCode-69 Were you able to figure this out? Or I can help?
It's happening because we're using a loop somewhere to render multiple items in a list and all of them have the same ( or empty ) key property. We can use the ReactDevTools to quickly figure this out. Let me know if you need help.

**Comment by noobCode-69** [comment]
I will be busy this week,  assigned to you

**Comment by alexdanilowicz** [comment]
Thanks for jumping in and offering mentorship, @Pranav2612000. Really appreciate that. Feel free to tackle this issue, I assigned it to you.
