### ISSUE TITLE
Color Picker: Allow user to manually enter HEX values

### ISSUE THREAD

**Issue by Pranav2612000** [Mirrorful/mirrorful#405]
Currently, the input boxes are disabled and the only way for a user to choose color is through the color picker.

<img width="1038" alt="image" src="https://github.com/Mirrorful/mirrorful/assets/20909078/e325f495-b71a-4da0-9316-781f22b6d148">

We also need to allow users to directly type in HEX and RGBA values.

**Comment by Pranav2612000** [comment]
@alexdanilowicz I had already started working on this before and I'll be happy to pick this up. The challenging part is handling invalid values. We can mimic the way Figma does it –

For HEX
`Invalid value` - e.g 'u' - revert back to the last valid value
`String greater than 6 chars` - Trim to six characters and apply the same rules
`String lesser than 6 chars` - Add 0's to make it 6 characters long
( Figma has more complex rules here, which I wasn't able to figure out, but I think these are good enough for us for now )

For RGB
`Invalid value` - e.g 'aaa' - revert back to the last valid value
`Number not in 0-255` - auto change to the closest valid number. i.e negative number change to zero and number greater than 255 change to 255. e.g `-300` changes to `0`, `20000` changes to `255`
`Fractions/Decimals` - auto change to the closest valid number e.g `22.9` changes to `23`, `221/10` changes to `22`

For Alpha/Opacity
`Invalid value` - e.g 'aaa' - revert back to the last valid value
`Number not in 0-100` - auto change to the closest valid number. i.e negative number change to zero and number greater than 100 change to 100. e.g `-300` changes to `0`, `20000` changes to `100`
`Fractions/Decimals` - Supported. Auto change to decimal representation( hundredth's place ) e.g `22.9` stays the same, `221/10` changes to `22.1`

**Comment by alexdanilowicz** [comment]
@Pranav2612000 want to split this into two issues, one for hex, one for rgba? Which one are you already working on?

**Comment by Pranav2612000** [comment]
I'll pick up the `HEX` one.

**Comment by alexdanilowicz** [comment]
Ok great, I changed title of this issue to just be HEX and I'll work on RGBA tomorrow.

**Comment by alexdanilowicz** [comment]
Thanks so much for noting how Figma handles it, very helpful! @Pranav2612000

**Comment by alexdanilowicz** [comment]
If you want, feel free to start the RGBA one too, otherwise, I'll do it tomorrow. 🎊
