### ISSUE TITLE
Colors Palette: Allow users to change color name by clicking on the Color name

### ISSUE THREAD

**Issue by Pranav2612000** [Mirrorful/mirrorful#407]
<img width="1111" alt="image" src="https://github.com/Mirrorful/mirrorful/assets/20909078/e4982107-59c1-4122-a586-95a64f731919">

For example, clicking on "Medium Purple" should show an input box that allows the user to modify the current name, instead of the user having to click on the pencil icon and then choose `Edit Color Name`

The user should be able to edit inline on the same page. Similar to how the UI of the HSL values boxes.

**Comment by Pranav2612000** [comment]
@alexdanilowicz Should double clicking the name open up the **Edit Color Name** modal? Or should the user be able to edit the name inline on the same page ( Using something like a tooltip ) ?

**Comment by alexdanilowicz** [comment]
@Pranav2612000 I updated the issue description! I think it should be inline, but not a tooltip. It should be an input box.

**Comment by alexdanilowicz** [comment]
Go for it @Bismay5467 !

**Comment by Pranav2612000** [comment]
It seems a little odd to move the edit button to the far-right. IMO it should always be next to the name.
> Colour names can have any length
What we could maybe do is keep the input fixed width. If the name is larger than the width, the text scrolls inside the input while typing. Once we save the name the new width takes effect.

**Comment by alexdanilowicz** [comment]
agreed @Pranav2612000  👍🏼 

cc @Bismay5467

**Comment by alexdanilowicz** [comment]
No, that is not the intended outcome. Also, we should check that it's not a color name that already exists, otherwise the color will be deleted. I made a new issue: https://github.com/Mirrorful/mirrorful/issues/425 want to take it on? I am merging this PR right now, so it can be a new PR. Great work!
