### ISSUE TITLE
Shadows: Change shadowpicker color picker to the new color picker 

### ISSUE THREAD

**Issue by Pranav2612000** [Mirrorful/mirrorful#408]
Update the Add/Edit Shadow Variant Modal to migrate away from the older color picker and use the newer color picker.

<img width="1013" alt="image" src="https://github.com/Mirrorful/mirrorful/assets/20909078/58a0d4b5-5b6d-4764-bcd1-2aa3047e61b1">

**Comment by joelcmk** [comment]
I can help with this!

**Comment by alexdanilowicz** [comment]
@joelcmk awesome, assigned to you! Thanks for picking this up! 🎊
