### ISSUE TITLE
Make the entire Mirrorful dashboard Mobile-friendly

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#409]
We should leverage Charka's responsive styles support: https://chakra-ui.com/docs/styled-system/responsive-styles

Everything should be mobile friendly and responsive.

**Comment by Pranav2612000** [comment]
@alexdanilowicz Can we break this down into smaller issues? I can start with the Onboarding flow.

**Comment by alexdanilowicz** [comment]
@Pranav2612000 definitely. Starting with onboarding flow would be awesome, thanks for your interest. Want to put up a PR for that and then we can break up into smaller issues. Are you familiar with how Charka responsive styles? https://chakra-ui.com/docs/styled-system/responsive-styles

Appreciate your help!

**Comment by sonylomo** [comment]
@alexdanilowicz I believe the other parts of this issue are the:
- [ ] Colors view
- [ ] Typography view
- [ ] Shadow view
- [ ] Export Tokens view

I'm a bit familiar with Chakra's responsive styles. I'd like to help out with the first 3 views I've mentioned; if this issue is still open for sharing. 🙂

**Comment by Pranav2612000** [comment]
> I'm familiar with Chakra's responsive styles. I'd like to help out with the views I've mentioned; if this issue is still open for sharing. 🙂

Sure it is. Thanks you for helping me @sonylomo 
I'm working on the Onboarding flow, you can work on any of the other pages.

**Comment by alexdanilowicz** [comment]
@sonylomo absolutely! Do you want to start with the sidebar?

**Comment by alexdanilowicz** [comment]
Reopening as it was closed by mistake.
