### ISSUE TITLE
When editing color name, check it is not empty or an existing color name

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#425]

**Comment by noobCode-69** [comment]
I have made all the required changes. Please review and meger!!

**Comment by noobCode-69** [comment]
what review!!

**Comment by alexdanilowicz** [comment]
Resolved by https://github.com/Mirrorful/mirrorful/pull/433

Thanks for your help @Bismay5467 and @noobCode-69!
