### ISSUE TITLE
Xs and disabled input on shadow modal looks off in dark mode

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#426]
<img width="416" alt="Screen Shot 2023-05-12 at 7 03 19 PM" src="https://github.com/Mirrorful/mirrorful/assets/29822597/b520e256-890e-4774-a44d-7aa4a06f8bd4">

**Comment by Pranav2612000** [comment]
From past communication with @noobCode-69 ( https://github.com/Mirrorful/mirrorful/issues/400#issuecomment-1545068773 ) He'll most probably be busy this week. 
Can you assign this to me? I'll take care of it.

**Comment by alexdanilowicz** [comment]
Assigned @Pranav2612000 ! Thank you.

**Comment by Pranav2612000** [comment]
Hey @alexdanilowicz Which disabled inputs is this issue talking about?

**Comment by alexdanilowicz** [comment]
@Pranav2612000 on the edit shadow variant, when you have multiple shadows

apologies because its not truly disabled. I should have used the term "faded out."

**Comment by Pranav2612000** [comment]
Oh. I've handled that in the PR.
