### ISSUE TITLE
Check if the user has clipboard api permissions, if they don't, request it

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#469]
https://web.dev/async-clipboard/#security-and-permissions
Relevant lines of code would be anywhere await navigator.clipboard is called.

**Comment by sonylomo** [comment]
I'd like to pick this up. 🙂

**Comment by alexdanilowicz** [comment]
Go for it @sonylomo. Assigned to you. Thank you! 🎉
