### ISSUE TITLE
add .nvmrc 

### ISSUE THREAD

**Issue by ashug0001** [Mirrorful/mirrorful#470]
I was setting up the repo on my local and I was using an older version of `node` `v16.17.1` and i kept getting following error 
```
The engine "node" is incompatible with this module. Expected version ">=18.12.1 <20.0.0". Got "16.17.1"
```

Maybe we can add `.nvmrc` in project root. So that we can simply do `nvm use` and start using the required `node` version

**Comment by alexdanilowicz** [comment]
Makes a lot of sense. Yes, you should be on `18.12.1`. Want to put in a PR? 

Feel free to join our slack community too! https://join.slack.com/t/mirrorful/shared_invite/zt-1ps2xtxh0-2NaixFfFzSKZbr5gw_AHfA

**Comment by ashug0001** [comment]
> Makes a lot of sense. Yes, you should be on `18.12.1`. Want to put in a PR?
> 
> Feel free to join our slack community too! https://join.slack.com/t/mirrorful/shared_invite/zt-1ps2xtxh0-2NaixFfFzSKZbr5gw_AHfA

Yeah, I'll raise a PR

**Comment by agupta0001** [comment]
hey @alexdanilowicz i've raised a PR. Also can you assign the issue to this account? I used @ashug0001 by mistake.

**Comment by alexdanilowicz** [comment]
Done! Just curious so that I can better understand the open-source contributors landscape. does the assignment matter because you track how many issues are assigned and closed by your account?

**Comment by agupta0001** [comment]
Hey @alexdanilowicz, I'm new to open source, infect this was my first open source contribution. I thought assignment was important, so I asked to change.
