### ISSUE TITLE
Mobile Responsiveness: Unable to rename colors

### ISSUE THREAD

**Issue by Pranav2612000** [Mirrorful/mirrorful#484]
The double click to edit option isn't working on pointing devices ( and isn't intuitive for mobiles, IMO ). And since we don't have a 'Edit name' option in the dropdown, there's no way for a mobile user to rename colors.

**Comment by Pranav2612000** [comment]
@alexdanilowicz What should the expected behaviour be? Should we add 'Edit Name' dropdown for mobile screen?

**Comment by alexdanilowicz** [comment]
@Pranav2612000 yes, let's add it back as we had it. I think the code is commented out, or just look in the git history and copy paste it back. Great issue, thanks for opening.

**Comment by Pranav2612000** [comment]
@alexdanilowicz Working on this. Will put up a PR tomorrow.
