### ISSUE TITLE
Move nextjs app (apps/web) back to using pages router instead of app router

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#496]
With the theme's page especially, it seems when you click to visit the theme's page for the first time, it loads all the content first, then routes you. 

This is because the app router is buggy.

**Comment by sonylomo** [comment]
I'd like to pick this up.

**Comment by alexdanilowicz** [comment]
Hi @sonylomo apologies for delayed response, I actually just did this and will merge this into the open source repo soon.
