### ISSUE TITLE
Add darkmode button to the top

### ISSUE THREAD

**Issue by Mohith234** [Mirrorful/mirrorful#500]
- The dark mode button is placed in the footer of the [website](https://mirrorful.com/). 
- It would enhance the user experience if it is present at the top in the Navbar

**Comment by rohitmondal03** [comment]
Hello @Mohith234, I really want to work on this issue. Can you please assign me this isseu ?

**Comment by alexdanilowicz** [comment]
Thanks for opening @Mohith234 and for jumping in @rohitmondal03, but the marketing site is actually a separate repo. So, I am closing this issue.
