### ISSUE TITLE
Autosave/Auto-export after making changes

### ISSUE THREAD

**Issue by Teddarific** [Mirrorful/mirrorful#53]
We should automatically export changes after the following actions:

* Adding a new color
* Editing a color
* Deleting a color

**Comment by prichter** [comment]
Would this by nature then create an expectation of "undo" functionality?

**Comment by alexdanilowicz** [comment]
Perhaps — but we can make undo functionality another issue to keep feature changes small! @prichter

**Comment by alexdanilowicz** [comment]
Assigning this to you @prichter. Thanks for taking it on! I replied to your Slack comment here: https://mirrorful.slack.com/archives/C04QKTVD8FP/p1677609775910159?thread_ts=1677583670.307909&cid=C04QKTVD8FP

**Comment by prichter** [comment]
Just so I'm clear, the expected functionality is when user adds / deletes / edits color, the changes are exported, writing to the relevant theme files in the same manner as clicking the export button, but without showing the dialog?
