### ISSUE TITLE
Recommend `hover` & `active` variants of colors

### ISSUE THREAD

**Issue by Teddarific** [Mirrorful/mirrorful#57]
![image](https://user-images.githubusercontent.com/16343600/221658611-2319bac1-1841-48a5-a252-beb802afc273.png)

Adding a new color right now can be intimidating / confusing because of the `hover` & `active` options. We should add a "magic wand" icon button that will prefill in a recommended shade. We can just prefill in `colorShades['600']` as the `hover`, and `colorShades['700']` as the `active`

**Comment by alexdanilowicz** [comment]
Hey @zachsnoek! Thanks so much and nice to meet you! Go for it. You're on fire 🔥 

Let us know if we can be helpful.
