### ISSUE TITLE
If a color is already set as primary or secondary, disabled the button and change it to say "Already set as primary"

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#59]
<img width="1340" alt="Screen Shot 2023-02-27 at 8 52 47 PM" src="https://user-images.githubusercontent.com/29822597/221757688-4db9dc28-4910-404d-94f3-4a4f8ddbe2a8.png">

**Comment by lagneshthakur** [comment]
I can help in fixing this.

**Comment by aryanraj60** [comment]
Hello! I would like to take ownership of this issue and work on resolving it. Could you please assign it to me? Thank you!

**Comment by alexdanilowicz** [comment]
@lagneshthakur to get started, after forking the repo, you can run the following commands:

```
➜  mirrorful git:(main) ✗ cd packages/mirrorful/editor
➜  mirrorful git:(main) ✗ git checkout -b "lagneshthakur/issue-59"
➜  mirrorful git:(paul/issue-53) ✗ yarn; cd editor; yarn; cd .. # install packages
➜  mirrorful git:(paul/issue-53) ✗ yarn run local # runs mirrorful locally

$ rm -rf ./dist; tsc --build; cross-env NODE_ENV=development node ./dist/cli/index.js
Running Mirrorful version: 2.0.19
Starting Mirrorful in /Users/zeus/code/mirrorful/packages/mirrorful.


Visit: http://localhost:5050/
Inside your project, you can run:

  yarn run mirrorful

to start the visual editor at any time 🚀
```
From there, you can then make changes in code and see the changes hotreload.

**Comment by lagneshthakur** [comment]
@alexdanilowicz Thank you, this is exactly what I was looking for.

**Comment by alexdanilowicz** [comment]
@lagneshthakur let us know if you need help!
