### ISSUE TITLE
Add dark mode to editor

### ISSUE THREAD

**Issue by tomByrer** [Mirrorful/mirrorful#61]
My concussion turned me into a pseudo-vampire, so this is partly an a11y issue.

Please add darkmode support to both the designer, then dogfood it in your homepage.
TIA

**Comment by alexdanilowicz** [comment]
Hey @tomByrer thanks for writing in and sorry to hear about your concussion. Head injuries suck 😞 . 

Dark mode is definitely on our roadmap that is the value of a theme after all! Should be able to add it this week.

**Comment by alexdanilowicz** [comment]
We use Charka under the hood, so would be best to follow docs here:
https://chakra-ui.com/docs/styled-system/color-mode

**Comment by lagneshthakur** [comment]
@alexdanilowicz - Please assign it to me.

**Comment by alexdanilowicz** [comment]
@lagneshthakur you still interested in this issue/still working on it? Just let us know! Also, if you're interested in doing a YouTube video, let us know. Hope everything is going well!

**Comment by alexdanilowicz** [comment]
Hey @lagneshthakur no worries as we've made a lot of changes to the dashboard and themeing. Teddy is also about to move Mirrorful to a monorepo set up, so no worries if you haven't started yet, just let us know. https://github.com/Mirrorful/mirrorful/pull/190

**Comment by lagneshthakur** [comment]
Yeah, I saw the monorepo change. Looks great.

And you're right, I haven't started on this one yet, will take a pull from the main branch for these changes and then start

**Comment by alexdanilowicz** [comment]
@lagneshthakur were you still interested in this one?

**Comment by alexdanilowicz** [comment]
go for it @Bismay5467

**Comment by alexdanilowicz** [comment]
Awesome, thank you @Bismay5467!

**Comment by alexdanilowicz** [comment]
#380 is a good start, but we really should use something like Mirrorful for this, or a top-level theming. Going to assign to @Teddarific and @alexdanilowicz (me) for now until we decide on best next steps.

**Comment by Teddarific** [comment]
This has been merged in 👯

**Comment by alexdanilowicz** [comment]
@tomByrer I think you'll like the new dark mode UI! https://app.mirrorful.com/colors

Thanks for opening the issue. Cheers 🎊 .

![darkmodemirrorful](https://github.com/Mirrorful/mirrorful/assets/29822597/6cef2c31-ec35-4088-93ca-ed38c2d313bf)
