### ISSUE TITLE
Color picker not appearing in edit color modal until an input has focus after refresh / initial load

### ISSUE THREAD

**Issue by prichter** [Mirrorful/mirrorful#66]
When the editor is initially loaded, a color picker does not initially appear when you open the color edit modal dialogue.  Clicking a color input activates the colour picker, but this perhaps should appear by default.

Loom of issue:  https://www.loom.com/share/63055c5daee240f0bca2d368ca62e771

Suggest `Polish` label

**Comment by alexdanilowicz** [comment]
Great feedback. Agreed. This should be a simple fix. Appreciate the Loom. Feel free to go for it if you want @prichter. Otherwise, happy to do it too.

**Comment by lagneshthakur** [comment]
@prichter  @alexdanilowicz  - Is this fixed? Unable to replicate.

**Comment by alexdanilowicz** [comment]
I don't think so, but don't worry about it

**Comment by prichter** [comment]
Fixed in pull request #74
