### ISSUE TITLE
Warning in console when picking optional color not previously set.

### ISSUE THREAD

**Issue by prichter** [Mirrorful/mirrorful#67]
Low priority issue I presume, but when a new color is added, and only the base color is set, if you select an optional color input(such as hover or active) and then click in the color picker, a react warning appears in the console:

<img width="1681" alt="image" src="https://user-images.githubusercontent.com/1085675/222108658-8630b899-3702-4665-8cec-85f881db8f4c.png">

Tidy up uncontrolled input required (?)

**Comment by alexdanilowicz** [comment]
Ah yes, I noticed this too, I think this is because the value of the input is originally blank. I think considering it's a warning it's ok for now, but definitely something we want to fix. Feel free to take a stab if you want @prichter!

**Comment by prichter** [comment]
Comments in EditColorModal.tsx indicate this needs backend fix?

**Comment by prichter** [comment]
Waiting for colorpicker to be reinstated before revisiting this...

**Comment by prichter** [comment]
Could not replicate this issue with new color pickers in the modal (probably because a default variant is added), so closing.
