### ISSUE TITLE
On editor startup, there is no initial indication if you have colors already defined - just the "Add new color" button

### ISSUE THREAD

**Issue by prichter** [Mirrorful/mirrorful#72]
If you have colors defined when you start mirrorful, you don't go through the onboarding process, rather your colors appear in the editor.  However, in between opening mirrorful and the colors loading asynchronously, there is no 'loading' indicator, you are merely faced with the "Add new color" button, with no indication that you have colors defined.

Add async loading indicator to editor in non-onboarding mode.

**Comment by alexdanilowicz** [comment]
Ah, we need to flesh out importing from your predefined theme. Going to close this for now as it's a bigger project, but great call out.
