### ISSUE TITLE
Add an empty `Add color variant` placeholder square

### ISSUE THREAD

**Issue by Teddarific** [Mirrorful/mirrorful#79]
![image](https://user-images.githubusercontent.com/16343600/222566942-3ee7c948-5c36-4ed7-bcef-454a7bd5301a.png)

**Comment by prichter** [comment]
Happy to do this if tomorrow is OK, please assign?

**Comment by prichter** [comment]
Working on this...

**Comment by alexdanilowicz** [comment]
Assigned! Go 🇦🇺 !!! haha
