### ISSUE TITLE
Display a small color box here (as we do in add/edit color modal)

### ISSUE THREAD

**Issue by alexdanilowicz** [Mirrorful/mirrorful#83]
<img width="665" alt="Screen Shot 2023-03-02 at 5 09 36 PM" src="https://user-images.githubusercontent.com/29822597/222606445-3477715a-ce5b-43da-9130-98b762086598.png">

**Comment by Teddarific** [comment]
I think ideally we also change this to the color picker as well — should be easier too with only one color to pick in the modal!
