### ISSUE TITLE
Create a Nuxt 3 example

### ISSUE THREAD

**Issue by tobiasdossinger** [Mirrorful/mirrorful#97]
Create an example in https://github.com/Mirrorful/mirrorful/tree/main/examples for Nuxt 3.

**Comment by tobiasdossinger** [comment]
Would like to assign it to myself 😄

**Comment by alexdanilowicz** [comment]
Go for it @tobiasdossinger. Are you a big user of Nuxt?

**Comment by alexdanilowicz** [comment]
I think this would be fantastic addition.

**Comment by tobiasdossinger** [comment]
Closed due to merged expample
